export const SUMMARY = [
  `≠ (Nonequality) denotes anything else other than = (Equality). = implies a singular answer, while ≠ encompasses limitless possibilities. However, we often prefer = over ≠, attempting false datificiation (Intangible_Ambiguity=Numerical_Value), or uncritical acceptance of algorithmic outcomes (Generative_AI=Truth). Like the overreliance on Recommendation Systems, some accept LLM-generated texts to be assuredly true.`,
  `≠ (Nonequality) is an interactive Multi-Device Web Art Installation integrating ChatGPT, Stable Diffusion, TTS, and WebSocket, presenting aggregated chaos - Where individual sections adhere to logic and algorithms, yet the overall experience emerges as illogical, deconstructed, and decentralised. It exposes the illogicality (≠) within seemingly logical systems (=).`,
];

export const DESCRIPTION = [
  `≠ (Nonequality) is an interactive Multi-Device Web Artwork that contends the world's complexity cannot be confined to equations alone. It objects to the notion that Algorithms, AIs, and LLMs can provide full comprehension of the real world. Audiences are encouraged to engage with this web-based installation using their mobile devices, with each tap triggering real-time changes across 4-channel screens.`,
  `The experience initiates with WebApp-powered screens presenting various equations, including Gaussian Distribution, Poisson Distribution, Modigliani-Miller Theorem, and others, each deeply embedded in contemporary societal applications. Audiences are guided to interact with their mobiles by scanning a displayed QR code. Upon entering the mobile website, an encyclopaedia-style interface unfolds, displaying a lengthy description of the initial equations. Audiences are nudged to click on blue hyperlink keywords, which recurrently lead to another encyclopaedia page. Each mobile keyword click dynamically influences all four screens in real time via Websocket. `,
  `Correspondingly, these screens generate interactive, algorithm-based audio-visual outcomes. The first channel features a Rhizomatic Database, exploring hypertext relationships between keywords. The second displays overlaid YouTube videos related to the clicked keyword, retrieved from the YouTube Data API. The remaining two engage in real-time conversation; The third channel generates accumulative ChatGPT dialogues with corresponding TTS, whilst the fourth responds with a repeated 'Ja,' reminiscent of a Nietzscheistic camel, blindly affirming whichever result is generated (Generative_AI=Truth). Scepticism towards this obedient ‘Ja’ intensifies until audiences reach the keyword '≠', when a transformation from ‘Ja’ to ‘Nein’ is triggered. Now the fourth screen opposes whichever the ChatGPT generates, representing a symbolic shift from the Nietzschean camel to the lion - An ability to oppose the a priori, transcending blind acceptance of ‘=’ and commencing to interplay the dynamics of '≠'. Hypertext transformation from mobile is now automated, unfolding in a nonlinear manner, guided by the relational structure of the rhizomatic database co-created in workshops led by the artist.`,
  `As audiences engage further, the 'Nein' proliferation accelerates, symbolically evolving from the Nietzschean lion to a baby, thus immersing them into the aggregated chaos. Although individual components of the artwork, such as ChatGPT conversations, Stable Diffusion-generated images, YouTube's RecSys, and TTS are inherently logical and algorithm-based, the collective audio-visual outcome from four channels is presented paradoxically as illogical, deconstructed, and decentralised. Here, out of orderly individual components emerges the collective chaos, where logic sums up to illogic, linearity accumulates into non-linear, and ‘=’ emerges into ‘≠’. `,
  `The interconnected nature of this Multi-Device Web Artwork, wherein audiences interact via their own mobile devices, enables them to closely entangle, embody, and immerse in the chaos of non-equilibrium triggered from their fingertips. This serves as a commentary on the use of technology in our daily lives, where individuals often passively consume algorithm-generated content from their mobiles. “≠” proposes an alternative future, using the same mobile devices not as a means of passively accepting ‘=’, but rather, as a means for active hyper-exploration, objection-to-norms, and playful facilitation of chaos.`,
];

export const CONCEPT = [
  `“≠” explores the theme of ‘Illogicality within seemingly logical systems’, referencing the idea explored from Peter Eisenman’s “Memorial to the Murdered Jews of Europe” [Rook-Koepsel, 2008]. This exploration resonates with the notion that the rational components can amalgamate to produce irrational outcomes, akin to Dostoevsky’s criticism of the Crystal Palace. Reflecting on the memorial's context, for instance, we are prompted to consider how the Nazis manipulated logical findings for irrational objectives.`,
  `A similar challenge coherently appears in contemporary society, where AI models, most notably LLMs, are embedded in our daily lives more than ever. Here raises the following questions:`,
  `Can we perceive that what they are generating is ‘truth’? Should we accept algorithmic results blindly? Can we ever assume that AI might be able to mimic our real world, and generate whatever is necessary within the world - and thus we no longer need humans in it?`,
  `Let us first reflect on the past decade to answer these questions. We have seen the rise of YouTube, Instagram, X, and other recommendation system-powered platforms. We have observed how people’s opinions can become polarised when uncritically accepting these algorithm-driven suggestions. Without cognitive engagement and resistance, individuals can easily become entrenched in extreme views, diverging further down a single smaller branch (opinion/perspective/algorithmic categorisation) of a ‘Tree’, losing sight of the bigger ‘Chunk’, left disentangled from other branches (opinions/perspectives/other categories). `,
  `What will be an alternative for the future of human-AI interaction, the future of generative AI co-existing with us? The previous reflection underscores the importance of embracing the ‘Rhizome’ over the ‘Tree’. Quoting from Deleuze and Guattari, ‘Rhizome’ - a network which connects one node to another without hierarchical order, sometimes even randomly - is used as a way people navigate through this artwork. Unlike algorithms that favour a tree-like structure, a hypertext transition promoting Rhizomatic structure/exposure/thinking could offer a viable alternative, preventing the replication of mistakes from the past decade, naturally accepting the non-linear pathway on facilitating the narrative rather than sticking with the linearity.`,
  `What can this hypertext transition enable? What can we discover from the Rhizomatic Structure? What is the significance of going beyond algorithms, logic, equations, and a priori? Referring to Wagner’s Tristan Chord - used as background music for this artwork - provides a good answer to this question. In the prelude of the opera “Tristan und Isolde”, Wagner uses a strange combination of notes, the sequence of F-B-D#-G#, which is “notoriously resistant to analysis” [Martin 2008]. This chord transcended the existing combination of harmonics, rejecting the existing mechanisms of chords to create a new melody and experience, which also heavily influenced later musicians like Debussy and Schönberg.`,
  `This is a form of non-linear transformation, a burst, a punctum, a moment of unique humane creation, which transcends the dynamics of pre-existing logic and equations. In the artwork “≠”, this is mirrored as 'Ja' transforming into 'Nein', and '=' evolving into '≠'. This hypertext transition facilitates navigation through a rhizomatic database, moving beyond the linear, the known, and the predetermined. Adhering solely to pre-established knowledge signifies stagnation, replacing the human domain with AI, akin to Nietzsche's metaphor of the camel, which acquiesces to pre-existing values, blindly responding ‘Ja’ to them. In the age of AI, remaining fixated on logic could spell the end of our existential purpose. This underlines the necessity of a Nietzschestic transformation – moving towards the Lion, then the Baby. The Lion has the ability to say ‘Nein’. How often have we rejected YouTube's algorithmic suggestions? In a world increasingly shaped by LLMs, will we be able to critically challenge generative outputs? `,
  `Those who can courageously say 'Nein', actively opposing, critiquing, and evaluating established a priori, might be able to embrace the unpredictability, randomness, chaos, and non-linearity - the Nietzschestic notion of Baby. It's no accident that many viewers of this artwork feel a sense of indescribable fear in the later stage of interaction, describing it as 'confronting with the apocalypse’. Indeed, it could signify the end of the world as we know it, but also the dawn of a 'new world' – fulfilled with a chaotic, non-equilibrium nature we may affirm and play around with within the post-GAI era. This is the future path humanity could take, the era of the Nietzschestic babies. Who is prepared to confront this future without fear? Who is prepared to welcome and reveal the chaotic nature of the world?`,
];

export const MEDIA = [
  `Multi-Device Web Artwork (MDWA), a term coined by the artist, is a web-based hybrid art form that integrates two or more physical devices, exploiting the real-time interconnectivity between devices as a means of interactive engagement, powered by WebSocket or WebRTC. MDWA critically re-examines the prevalent use of technical devices in isolation, challenging the normative engagement with mobile devices, the solitary focus of AR applications, and the segregating nature of HMD devices from the external environment. Central to MDWA is the principle of inter-device connectivity, fostering an expansion of cognitive awareness beyond a singular device. This interconnectedness transforms individual interactions into a collective immersive spatial experience, encompassing both the physical environment and the presence of others. `,
  `Specifically within the art gallery setting, MDWA catalyses a venture into cognitive realms previously unexplored, where control exerted from one device resonates and transforms the surrounding space. This phenomenon often elicits reactions of wonder and deeper engagement with the artwork, transcending passive observation, and triggering active participation. This heightened engagement resonates with Nietzsche’s concept of Will-to-power; the realisation that one’s actions on a singular device can propagate change in their environment embodies a tangible experience of their puissance. MDWA presents a vision of a more communal, engagement-driven society, where digital technology intertwines with the tangible world, countering the trend towards individualism and disconnection from the real.`,
  `In the artwork “≠”, MDWA serves as more than just an immersive and interactive platform; it stands as a metaphorical critique of our daily interactions with digital devices. In our routine lives, mobile phones are predominantly passive tools for consuming algorithm-driven content, a symbol of acquiescence to the '='. In contrast, “≠” encourages users to engage with their mobile devices in a more dynamic, hypertextual, and rhizomatic manner. This non-linear mode of interaction, coupled with the immediate audio-visual impact on the audience’s environment via screens surrounding them, exemplifies how active, divergent engagements with technology can reshape and redefine our physical spaces. The deliberate choice to use personal mobile phones for interaction within the installation underscores the potential of these ubiquitous devices to foster diverse, dynamic, and socially engaged experiences. This symbolically extends beyond mobile phones to other devices and different forms of HAI, challenging the superficial reflection on contemporary digital technology.`,
  `Technically, “≠” incorporates a React-based Next.js Web Application, enabling real-time communication between devices and browsers through WebSocket. This setup is complemented by the real-time generation of ChatGPT dialogues and TTS speeches. The foundation of this interactive experience is a pre-stored Rhizomatic Database, which maps the interconnectedness of keywords and integrates Stable Diffusion-generated images, Recommendation System (Youtube API)-generated YouTube video links, and ChatGPT-generated encyclopaedic descriptions. D3.js was used to visualise the node-edge relationship of the Rhizomatic Database.`,
];
